server:
  port: 8082

spring:
  application:
    name: ai-enterprise-service
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 128MB
  data:
    redis:
      host: 192.168.10.100
      port: 6379
      username: default
      password: 123456
      database: 0

app:
  deepseek:
    api-key:
    base-url: https://api.deepseek.com
    chat-model: deepseek-chat
  zhipu:
    api-key:
    base-url: https://open.bigmodel.cn/api/paas/v4
    embedding-model: embedding-3
  knowledge:
    upload-dir: backend/data/uploads
    metadata-file: backend/data/knowledge-metadata.json
  redis-vector:
    index-name: ai_service_embedding_index
    prefix: "embedding:"
    dimension: 2048

cors:
  allow-origins: "*"
  allow-methods: "GET,POST,OPTIONS"
  allow-headers: "*"

netty:
  websocket:
    port: 8083
    path: /ws/chat

julog:
  logpath: backend/logs/ai-service.log
